pr:
  - master

trigger:
  - master

variables:
  - group: fabric-variables

jobs:
  - job: Build
    pool: Docker Build
    steps:
    # TODO: remove, temporarily disabled to speed debugging
    - checkout: none
      clean: false

    # TODO: uncomment, temporarily disabled to speed debugging
    # - template: azure-pipelines.tools.yml

    # - script: |
    #     yarn
    #   displayName: yarn

    # - script: |
    #     npm run checkchange
    #   displayName: check change

    # - script: |
    #     npm run buildci
    #   displayName: build ci

    # - task: AzureUpload@1
    #   displayName: Upload PR deploy site
    #   inputs:
    #     SourcePath: 'apps/pr-deploy-site/dist'
    #     azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
    #     storage: fabricweb
    #     ContainerName: '$web'
    #     BlobPrefix: 'pr-deploy-site/$(Build.SourceBranch)'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.Repository.LocalPath)
        includeRootFolder: true
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: $(Build.ArtifactStagingDirectory)/build.tar.gz
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: Build

  - job: PerfTest
    pool: Docker Test
    dependsOn: Build
    steps:

    # Perf test uses PR bundle deployed to PR deploy site and therefore does not need previously built artifacts.
    # We just need to do a tools install.
    - template: azure-pipelines.tools.yml

    - script: |
        yarn
      displayName: yarn

    - script: |
        npm run just run-perf-test
      workingDirectory: apps/perf-test
      displayName: Perf Test

    - task: AzureUpload@1
      displayName: Upload Perf Test Result to PR deploy site
      inputs:
        SourcePath: 'apps/perf-test/dist'
        azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
        storage: fabricweb
        ContainerName: '$web'
        BlobPrefix: 'pr-deploy-site/$(Build.SourceBranch)/perf-test'

    - task: GithubPRComment@0
      displayName: 'Post Perf Results to Github Pull Request'
      inputs:
        githubOwner: OfficeDev
        githubRepo: 'office-ui-fabric-react'
        blobFilePath: '$(Build.SourcesDirectory)/$(PerfCommentFilePath)'
        status: '$(PerfCommentStatus)'
        uniqueId: 'perfComment9423'

    - task: GithubPRStatus@0
      displayName: 'Update Github Pull Request Status'
      inputs:
        githubOwner: OfficeDev
        githubRepo: 'office-ui-fabric-react'
        githubContext: 'Pull Request Deployed Site'
        githubDescription: 'Click "Details" to go to the Deployed Site'
        githubTargetLink: 'http://fabricweb.z5.web.core.windows.net/pr-deploy-site/$(Build.SourceBranch)/'

  - job: VRTest
    pool: Docker Test
    dependsOn: Build
    steps:
    # No need for checkout since we're using build artifacts.
    - checkout: none

    - download: current
      artifact: Build

    - task: ExtractFiles@1
      inputs:
        # By default, patterns start in the root folder of the repo (same as if you had specified $(Build.SourcesDirectory)).
        # Pipeline.Workspace is one level up.
        archiveFilePatterns: '../Build/*.tar.gz'
        # archiveFilePatterns: '../*.tar.gz'
        # This is really bad and hacky, but this task requires relative pathing. It'd be nice to use the environment variables, instead.
        # Might be better to use a bash task to allow for use of environment variables.
        destinationFolder: '..'
        # destinationFolder: $(Build.Repository.LocalPath)
        cleanDestinationFolder: false

    - script: |
        git config --global user.email "fabrictactical@microsoft.com"
        git config --global user.name "Fabric Tactical"
        npm run vrtest -- --debug
      displayName: run VR Test
      env:
        SCREENER_API_KEY: $(screener.key)

    - script: |
        npm run check-for-changed-files
      displayName: check for change file

    # a11y-tests disabled until occasional local and CI timeout issue can be resolved.
    # If/when re-enabled, should probably be made as a standalone job (or appended to another test job.)
    #- task: PublishBuildArtifacts@1
    #  inputs:
    #    pathtoPublish: './apps/a11y-tests/dist/reports'
    #    artifactName: 'CodeAnalysisLogs'
    #  displayName: publish sarif a11y reports
