name: Bundle size | Comment on PR
on:
  workflow_run:
    workflows: ['Bundle size']
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }} && ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: monosize-report
          path: ./results
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load PR number
        id: pr_number
        run: echo "id=$(cat pr.txt)" >> $GITHUB_OUTPUT
        working-directory: ./results

      - name: 'Comment on PR'
        uses: marocchino/sticky-pull-request-comment@d2ad0de260ae8b0235ce059e63f2949ba9e05943 # v2.9.3
        with:
          header: bundle-size-report
          number: ${{ steps.pr_number.outputs.id }}
          path: ./results/monosize-report.md
