# Workflow name
name: 'Docsite publish to Chromatic'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'applying package updates') || github.event_name == 'workflow_dispatch' }}

    outputs:
      status: ${{ steps.verify-react-components-changed.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout [master]

      - name: Verify react-compoenents has changed
        uses: tj-actions/changed-files@v41
        id: verify-react-components-changed
        with:
          files: |
            packages/react-components/react-components/package.json
  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'true'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build dependencies
        uses: ./.github/actions/build-to
        with:
          workspaces: '@fluentui/public-docsite-v9'
          backfill-cache-provider-options: ${{ secrets.BACKFILL_CACHE_PROVIDER_OPTIONS }}

      - name: Publish to Chromatic
        run: yarn workspace @fluentui/public-docsite-v9 chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
