# Workflow name
name: 'Docsite publish'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'applying package updates') || github.event_name == 'workflow_dispatch' }}

    outputs:
      status: ${{ steps.verify-react-components-changed.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]

      - name: Verify react-compoenents has changed
        uses: tj-actions/changed-files@v23.1
        id: verify-react-components-changed
        with:
          files: |
            packages/react-components/react-components/package.json
  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'true'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build dependencies
        run: yarn build --to @fluentui/public-docsite-v9

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: apps/public-docsite-v9
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
