name: Pull request housekeeping ðŸ§¹
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
  assign-to-current-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to latest milestone
        uses: andrefcdias/add-to-milestone@v1.2.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          use-expression: true
          milestone: '* Project Cycle *'
          users-file-path: '.github/MAINTAINERS'
