name: VRT CI | Comment on PR
on:
  workflow_run:
    workflows: ['VRT POC']
    types:
      - completed

concurrency:
  # see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_PARALLEL: 4 # ubuntu-latest = 4-core CPU / 16 GB of RAM | macos-14-xlarge (arm) = 6-core CPU / 14 GB of RAM
  NX_PREFER_TS_NODE: true
  NX_VERBOSE_LOGGING: true

jobs:
  run_vr_diff:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }} && ${{ github.event.workflow_run.event == 'pull_request' }}
    outputs:
      pr_number: ${{ steps.pr_number.outputs.result }}
    permissions:
      # necessary to write comments to the PR from the vr-approval-cli
      pull-requests: write
      # id-token: write
    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     sparse-checkout: |
      #       .github

      # - uses: actions/download-artifact@v4
      #   with:
      #     name: vrt_report
      #     path: ./vrt_report
      #     run-id: ${{ github.event.workflow_run.id }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: pr-number
          path: ./results
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load PR number
        id: pr_number
        run: echo "id=$(cat pr.txt)" >> $GITHUB_OUTPUT
        working-directory: ./results

      - name: 'Comment on PR'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vr-report-comment
          number: ${{ steps.pr_number }}
          message: |
            VR Regression Report:
            - status: ${{ github.event.workflow_run.conclusion }}
            - check whole [report](${{github.event.workflow_run.workflow_url}}) to review visual differences
