name: VRT PR
on:
  pull_request:
    branches:
      # Why only master - https://github.com/microsoft/fluentui/pull/34072#discussion_r2011220032
      - master

concurrency:
  # see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_PARALLEL: 6 # ubuntu-latest = 4-core CPU / 16 GB of RAM | macos-14-xlarge (arm) = 6-core CPU / 14 GB of RAM
  NX_PREFER_TS_NODE: true
  NX_VERBOSE_LOGGING: true

permissions:
  contents: 'read'
  actions: 'read'

jobs:
  generate_vrt_screenshots:
    if: ${{ github.repository_owner == 'microsoft' }}
    runs-on: macos-14-xlarge
    name: Generate screenshots
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4.3.3
        with:
          main-branch-name: 'master'

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - run: yarn install --frozen-lockfile
      - run: yarn playwright install --with-deps

      - name: Run VR tests (generate screenshots)
        run: yarn nx affected -t test-vr --nxBail

      - name: Prepare VR screenshots for upload
        uses: actions/github-script@v7
        id: screenshots_root
        with:
          script: |
            const run = require('./.github/scripts/prepare-vr-screenshots-for-upload');
            const config = {
              projects: ['vr-tests-web-components', 'vr-tests-react-components', 'vr-tests']
            };
            const result = await run({github,context,core,config});
            return result;
          result-encoding: string

      - name: Upload VR screenshots
        uses: actions/upload-artifact@v4
        with:
          name: vrscreenshot
          retention-days: 1
          path: ${{steps.screenshots_root.outputs.result}}

      - name: Save PR number
        run: echo ${{ github.event.number }} > pr.txt

      - uses: actions/upload-artifact@v4
        with:
          name: pr-number
          retention-days: 1
          if-no-files-found: error
          path: |
            pr.txt
