name: Screener build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  DEPLOYHOST: 'fluentuipr.z22.web.core.windows.net'

jobs:
  environment-upload:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir artifacts

      ###########################################
      # BROWSERSLIST_IGNORE_OLD_DATA = Prevents failures on CI when "caniuse-lite" becomes outdated
      # DEPLOYHOST = address of host for screener tests deployment
      # BUILD_BUILDID = unique ID of the workflow run within the repo
      # BUILD_SOURCEBRANCH = branch that triggered the workflow -> refs/pull/<pr_number>/merge
      ###########################################
      - name: Set base env variables
        run: |
          cat <<EOT >> artifacts/environment
          BROWSERSLIST_IGNORE_OLD_DATA=true
          DEPLOYHOST='fluentuipr.z22.web.core.windows.net'
          BUILD_BUILDID=${{ github.run_id }}
          BUILD_SOURCEBRANCH=${{ github.ref }}
          SCREENER_BUILD=1
          EOT

      - name: Set env variables if there is not a PR
        run: |
          cat <<EOT >> artifacts/environment
          DEPLOYBASEPATH=heads/${{github.ref_name}}
          DEPLOYURL=https://${{env.DEPLOYHOST}}/heads/${{github.ref_name}}
          BUILD_SOURCEBRANCHNAME=${{ github.ref_name }}
          EOT
        if: github.event_name == 'push'

      - name: Check if draft PR has 'Ready for VR' label
        uses: actions/github-script@v6
        with:
          script: |
            let labels = await github.rest.issues.listLabelsOnIssue({
              issue_number: ${{github.event.pull_request.number}},
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            let foundLabel = labels.data.find((label) => {return label.name == 'Ready for VR'});
            if(foundLabel === undefined)
            core.exportVariable('SKIP_SCREENER', true);
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == true

      - run: echo "SKIP_SCREENER=${{env.SKIP_SCREENER}}" >> skip-screener

      - name: Upload environment variables artifact
        uses: actions/upload-artifact@v3
        with:
          name: skip-screener
          path: skip-screener

      ###########################################
      # SYSTEM_PULLREQUEST_TARGETBRANCH = target branch name
      # SYSTEM_PULLREQUEST_SOURCEBRANCH = source branch name
      # SYSTEM_PULLREQUEST_PULLREQUESTID = ID of the PR
      # SYSTEM_PULLREQUEST_SOURCECOMMITID = commit SHA of PR
      # DEPLOYBASEPATH = path for deploy URL -> pull/<pr_number> for PRs
      # DEPLOYURL= address for tests deployment, uses DEPLOYHOST and DEPLOYBASEPATH
      # BUILD_SOURCEBRANCHNAME = 'merge' for PRs
      ###########################################
      - name: Set env variables if there is a PR
        run: |
          cat <<EOT >> artifacts/environment
          SYSTEM_PULLREQUEST_TARGETBRANCH=${{ github.event.pull_request.base.ref }}
          SYSTEM_PULLREQUEST_SOURCEBRANCH=${{ github.event.pull_request.head.ref }}
          SYSTEM_PULLREQUEST_PULLREQUESTID=${{ github.event.pull_request.id }}
          SYSTEM_PULLREQUEST_SOURCECOMMITID=${{ github.event.pull_request.head.sha }}
          DEPLOYBASEPATH=pull/${{github.event.pull_request.number}}
          DEPLOYURL=https://${{env.DEPLOYHOST}}/pull/${{github.event.pull_request.number}}
          BUILD_SOURCEBRANCHNAME='merge'
          EOT
        if: ${{ github.event_name == 'pull_request' && env.SKIP_SCREENER == ''}}

      - name: Upload environment variables artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-artifact
          path: artifacts/environment
        if: ${{env.SKIP_SCREENER == ''}}

    outputs:
      SKIP_SCREENER: ${{env.SKIP_SCREENER}}

  screener-react-northstar:
    if: needs.environment-upload.outputs.SKIP_SCREENER == ''
    needs: environment-upload
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react-northstar
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download env variables artifact
        uses: actions/download-artifact@v3
        with:
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/docs --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if northstar packages were affected

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build FUI N* VR Test
        run: yarn workspace @fluentui/docs vr:build
        env:
          SCREENER_BUILD: 1
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: northstar-artifact
          path: packages/fluentui/docs/dist
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

  screener-react:
    if: needs.environment-upload.outputs.SKIP_SCREENER == ''
    needs: environment-upload
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/vr-tests --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if v8 packages were affected

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build vr-tests storybook
        run: yarn workspace @fluentui/vr-tests screener:build
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: screener-artifact
          path: apps/vr-tests/dist/storybook
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

  screener-react-components:
    if: needs.environment-upload.outputs.SKIP_SCREENER == ''
    needs: environment-upload
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react-components
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/vr-tests-react-components --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if v9 packages were affected

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build vr-tests-react-components storybook
        run: yarn workspace @fluentui/vr-tests-react-components screener:build
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: vnext-artifact
          path: apps/vr-tests-react-components/dist/storybook
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}
